### ISSUE TITLE
Indices for shaped arrays need manually coerced to numbers

### ISSUE THREAD

**Issue by donaldh** [rakudo/rakudo#1297]
## The Problem
Using variable as shaped array index `@matrix[$x; $y]` only works if variable is a numeric type. Fails for Str, Match, etc.
```
> my @matrix[2;2]; @matrix['0'; '0'] = True
Partially dimensioned views of shaped arrays not yet implemented. Sorry.
  in block <unit> at <unknown file> line 1
```
Manually:
```
> my @matrix[2;2]; @matrix[+'0'; +'0'] = True
True
```
## Expected Behavior
Same as one-dimensional arrays:
```
> my @array; @array['2'] = True
True
```

## Environment
* Operating system: macOS High Sierra
* Compiler version (`perl6 -v`): 
This is Rakudo version 2017.10-4-g4fca94743 built on MoarVM version 2017.11-20-gd23f5ca16
implementing Perl 6.c.

**Comment by lizmat** [comment]
Fixed with 00632edb6f3895f715c9 , tests needed.

Note: at the moment, this seems to tickle a bug in the MoarVM JIT logic, e.g. when doing something like:

my @matrix[2;2] = [1,2],[3,4]; @matrix[<0>;0] for ^1000000;

However, make spectest is clean with this, so probably is of no consequence in normal operation.

**Comment by zoffixznet** [comment]
@lizmat I wrote [the tests](https://github.com/perl6/roast/commit/469ebbc75b8adda58c927badc34f808ab1f1fb14) to cover this, but looks like the issue still exists.

**Comment by usev6** [comment]
Yes, this is still (or again) failing:
```
$ ./rakudo-m -e 'my @matrix[2;2]; @matrix["0"; "0"] = 42'
Partially dimensioned views of shaped arrays not yet implemented. Sorry.
  in block <unit> at -e line 1
```

**Comment by ab5tract** [comment]
Apparently fixed in RakuAST:

```
> set-rakuast; r 'my @matrix[2;2]; dd @matrix["0"; "0"] = 42'
42
```
