### ISSUE TITLE
Error missing declared signature if `where` clause is used in proto

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1746]
***See [Newcomer Guide to Contributing to Core Perl 6](https://rakudo.party/post/Newcomer-Guide-to-Contributing-to-Core-Perl-6) for tips on fixing this Issue***

----------------

Normally, this message tells you what the declared signature is (in this case, `(Int)`):
```
$ perl6 -e 'sub z(Int) {}; z "x"'
===SORRY!=== Error while compiling -e
Calling z(Str) will never work with declared signature (Int)
```

But if you use a `where` clause and stick it into `proto`, the `with declared signature` part doesn't say what the declared signature is:
```
19:39 	Zoffix 	m: proto z($ where rand) {*}; say z "x"
19:39 	camelia 	rakudo-moar 9e6ae276a: OUTPUT: «5===SORRY!5=== Error while compiling <tmp>␤Calling z(Str) will never work with declared signature ␤at <tmp>:1␤------> 3proto z($ where rand) {*}; say 7⏏5z "x"␤»
```

**Comment by jsimonet** [comment]
In addition, using a where clause causes the signatures to be evaluated at runtime. If a multi is specified, the error is a TypeCheck Exception.
```
perl6 --stagestats -e 'proto z( $ where rand ) {*}; multi z($ where rand){}; say z "x"'
Stage start      :   0.000
Stage parse      :   0.147
Stage syntaxcheck:   0.000
Stage ast        :   0.000
Stage optimize   :   0.004
Stage mast       :   0.009
Stage mbc        :   0.000
Stage moar       :   0.000
Constraint type check failed in binding to parameter '<anon>'; expected anonymous constraint to be met but got Str ("x")
  in block <unit> at -e line 1
```

**Comment by jsimonet** [comment]
Tried to implement a fix in PR #1868

**Comment by dolmen** [comment]
This looks fixed in rakudo star 2018.06:
```
$ perl6 -e 'proto z($ where rand) {*}; say z "x"'
===SORRY!=== Error while compiling -e
Calling z(Str) will never work with declared signature
at -e:1
------> proto z($ where rand) {*}; say ⏏z "x"
```

**Comment by zoffixznet** [comment]
> Tried to implement a fix in PR #1868

Commented on the PR.

> This looks fixed in rakudo star 2018.06:

That's still missing what the declared signature is.

**Comment by tinmarino** [comment]
I made PR #3558 creating a new Exception class. Then realized that #1868 handled it better. But got Blocked.
How to unblock it ?
