### ISSUE TITLE
[WIP] Blin 2019-08-20

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3132]
- [x] ASN::META – Fail, Bisected: 2ee82afe6e6713c26b929e2855ea05d8eb3b9fee (should be fixed now, but see https://github.com/rakudo/rakudo/issues/3133)
 - [x] Grammar::PrettyErrors – Fail, Bisected: da65fb5baec836bfbda7241c0263b9a6212df6d7
 - [ ] Unicode::GCB – Fail, Bisected: f5ef0b3cafe6afabc07b0300e38da1007736835c

All these should be fixed with https://github.com/rakudo/rakudo/commit/0dd6573a45f61652a2c5166468362e71562f6dd7:
 - [x] DBIish – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc
 - [x] GraphQL – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc
 - [x] MinG – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc
 - [x] URI::Template – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc
 - [x] XML::Class – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc
 - [x] YAMLish – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc
 - [x] Yapsi – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc

Raw Blin files: https://usercontent.irccloud-cdn.com/file/Kuaq7HLm/blin-output-2019-08-20.tar.gz

Previous ticket: https://github.com/rakudo/rakudo/issues/3113

From the previous ticket (we need to figure out what was wrong there anyway):
- [ ] Smack – Fail, Bisected: fcf1f761a1da6465b4ffe9c175993ba4555bf49f

**Comment by AlexDaniel** [comment]
There's a golf for c7056f2 issues here: https://github.com/rakudo/rakudo/commit/c7056f2071af2b7a99de4a5bda8568e2b435e8bc#commitcomment-34749749

**Comment by salortiz** [comment]
@AlexDaniel, 
The issue with c7056f2 was fixed with 0dd6573a
Regards.

**Comment by AlexDaniel** [comment]
Yes, got that! Thank you!

**Comment by AlexDaniel** [comment]
From the last Blin run:
* API::USNavalObservatory – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* App::AizuOnlineJudge – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* App::Assixt – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* App::Tasks – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Audio::Icecast – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Config::Parser::yaml – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Cro::Core – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Cro::HTTP::Test – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Cro::OpenAPI::RoutesFromDefinition – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Cro::RPC::JSON – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Cro::WebApp – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* CroX::HTTP::FallbackPassthru – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* FanFou – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Hastebin – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* I18n::Simple – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* LogP6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* LogP6-Writer-Journald – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Magento – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Monitor::Monit – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Net::Telnet – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Oddmuse6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* OpenAPI::Model – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Sparrow6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Template::Classic – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Test::HTTP::Server – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Tomtit – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* Tomty – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
* WebService::Soundcloud – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67

Ping @vrurg.

> \<japhb\> AlexDaniel: Not looking at the tarball, but if you're seeing a lot of failed installs, it might be because YAMLish won't install right now.  Author is aware.
> \<japhb\> https://github.com/Leont/yamlish/issues/29

Blin output: https://usercontent.irccloud-cdn.com/file/FuRvVGH3/blin-output-2019-08-29.tar.gz

**Comment by AlexDaniel** [comment]
- [ ] RDF::Turtle – Fail, Bisected: b21a57763cad96b6e70b14833e22d83f7bc4c8bf – Something related to grammar .parse

**Comment by jnthn** [comment]
About 43066b9d03c01d5ca8b6ca0203c90c609af5cd67, I mentioned when the 6.e grammar base class was being discussed that there should also be another meta-class (a 6.e GrammarHOW), which the 6.e BOOTSTRAP can then configure with the 6.e Grammar. That meta-class can go either in BOOTSTRAP or even in the 6.e setting. That would avoid this issue. Trying to do it with the approach taken here is not going to end well.

**Comment by AlexDaniel** [comment]
Other bisected modules, but these may be a bit spurious:
- [ ] CoreHackers::Sourcery – Fail, Bisected: c94f5db60e3c5929cccd142037795755c4f05f98
- [ ] Cro::WebSocket – Fail, Bisected: 38aa128ca9d8fec34ccdf84c72c5ab41224d48ab
- [ ] Grammar::PrettyErrors – Fail, Bisected: da65fb5baec836bfbda7241c0263b9a6212df6d7
- [ ] Proc::Q – Fail, Bisected: f53c8288acae55200e0385af349f31870c889150

**Comment by vrurg** [comment]
I think most of the problems related to 43066b9 are caused by broken `TAP` module. I already know what's the problem is.

@jnthn I would still be in favor of avoiding version-specific metaclasses.

**Comment by jnthn** [comment]
> I think most of the problems related to 43066b9 are caused by broken TAP module. I already know what's the problem is.

I think they're all because we find the wrong `Grammar`, because it's perfectly fine (and even fairly common) for modules to use that name within a module, and so have it registered lexically.

> I would still be in favor of avoiding version-specific metaclasses.

Why? If we did that, we'd not have the problem exhibited here. And, more deeply, it feels entirely right to me: the default parent is a meta-behavior, and if we're already having another version of a behavior, I don't see why we shouldn't have another version of the related meta-behavior too.

**Comment by vrurg** [comment]
> I think they're all because we find the wrong `Grammar`, because it's perfectly fine (and even fairly common) for modules to use that name within a module, and so have it registered lexically.

Aha. I had limit symbol lookup to setting, but used lexical lookup on client.
 
> Why? If we did that, we'd not have the problem exhibited here. And, more deeply, it feels entirely right to me: the default parent is a meta-behavior, and if we're already having another version of a behavior, I don't see why we shouldn't have another version of the related meta-behavior too.

`Perl6::Metaclass::Grammar6eHOW`? Definitely not. 

Language-specific meta? Should be possible, but not yet supported by the build subsystem. I have started process of merging common parts of moar and jvm makefiles and it turns out to be even more time consuming than I expected. 

But otherwise the first thing coming to my mind is `Perl6::Metamodel::v6<rev>` and `use Perl6::Metamodel::v6<rev>;` in revision's `BOOTSTRAP`.

**Comment by vrurg** [comment]
- [ ] API::USNavalObservatory – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] App::AizuOnlineJudge – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] App::Assixt – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] App::Tasks – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Audio::Icecast – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Config::Parser::yaml – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::Core – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::HTTP::Test – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::OpenAPI::RoutesFromDefinition – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::RPC::JSON – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::WebApp – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] CroX::HTTP::FallbackPassthru – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] FanFou – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Hastebin – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] I18n::Simple – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] LogP6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] LogP6-Writer-Journald – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Magento – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Monitor::Monit – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Net::Telnet – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Oddmuse6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] OpenAPI::Model – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Sparrow6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Template::Classic – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Test::HTTP::Server – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Tomtit – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Tomty – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] WebService::Soundcloud – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67

**Comment by vrurg** [comment]
rakudo/rakudo#3154 fixes all reported modules except for `Grammar::PrettyErrors`. I will merge the PR and then proceed with the latter. Though due to approaching hurricane not sure how much time would I have these days.

**Comment by AlexDaniel** [comment]
Thank you, @vrurg! Please take care.

**Comment by vrurg** [comment]
Re-implementing #3154 to conform with @jnthn request. Thus, all module checks would be re-done.

**Comment by vrurg** [comment]
`Grammar::PrettyErrors` got a PR bduggan/p6-grammar-prettyerrors#1

**Comment by vrurg** [comment]
All failures fixed with c757ada6f3caa21cd4549316d7f8df8c02ecb110 and with the above mentioned PR.

**Comment by AlexDaniel** [comment]
Here are the latest results. Seems previous issues are not resolved? @vrurg, can you check?

Raw data: https://usercontent.irccloud-cdn.com/file/WWEU5lHe/blin-output-2019-09-06.tar.gz

- [ ] API::USNavalObservatory – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] App::AizuOnlineJudge – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] App::Assixt – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] App::Tasks – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Audio::Icecast – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Config::Parser::yaml – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::Core – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::HTTP::Test – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::OpenAPI::RoutesFromDefinition – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::RPC::JSON – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Cro::WebApp – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] CroX::HTTP::FallbackPassthru – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] FanFou – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Hastebin – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] I18n::Simple – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] LogP6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] LogP6-Writer-Journald – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Magento – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Monitor::Monit – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Net::Telnet – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Oddmuse6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] OpenAPI::Model – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Sparrow6 – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Template::Classic – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Test::HTTP::Server – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Tomtit – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] Tomty – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- [ ] WebService::Soundcloud – Fail, Bisected: 43066b9d03c01d5ca8b6ca0203c90c609af5cd67
- ----
- [ ] ASN::META – Fail, Bisected: 2ee82afe6e6713c26b929e2855ea05d8eb3b9fee
- [ ] Cro::WebSocket – Fail, Bisected: 38aa128ca9d8fec34ccdf84c72c5ab41224d48ab
- ----
- [ ] DNS::Zone – Fail, Bisected: b21a57763cad96b6e70b14833e22d83f7bc4c8bf
- [ ] RDF::Turtle – Fail, Bisected: b21a57763cad96b6e70b14833e22d83f7bc4c8bf
- [ ] TAP – Fail, Bisected: b21a57763cad96b6e70b14833e22d83f7bc4c8bf
- ----
- [ ] URI::Template – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc
- [ ] YAMLish – Fail, Bisected: c7056f2071af2b7a99de4a5bda8568e2b435e8bc
- ----
- [ ] CoreHackers::Sourcery – Fail, Bisected: c94f5db60e3c5929cccd142037795755c4f05f98
- [ ] Grammar::PrettyErrors – Fail, Bisected: da65fb5baec836bfbda7241c0263b9a6212df6d7
- [ ] Proc::Q – Fail, Bisected: f53c8288acae55200e0385af349f31870c889150
- [ ] Unicode::GCB – Fail, Bisected: f5ef0b3cafe6afabc07b0300e38da1007736835c

**Comment by vrurg** [comment]
@AlexDaniel check if it was ran against `HEAD` and there was no mistake. `Cro::Core` on freshly build `HEAD` from official repo, not the fork of mine:

```
🅸 ttys000 vrurg@beetle ~/s/P/c/cro-core ⇒ prove6 -l                                                                                                                                                                                                                                                                                                           -1- 06-09-19 10:49:49 [master]
t/composer.t ................ ok
t/connection-conditional.t .. ok
t/connection-state.t ........ ok
t/iri.t ..................... ok
t/mediatype.t ............... ok
t/message-with-body.t ....... ok
t/tcp.t ..................... ok
t/uri.t ..................... ok
All tests successful.
Files=8, Tests=1164,  11 wallclock secs
Result: PASS
```

There must be something else.

**Comment by AlexDaniel** [comment]
@vrurg thank you for your work!

It's time for a new ticket.
