### ISSUE TITLE
libperl6_ops_moar.so installed in wrong directory

### ISSUE THREAD

**Issue by dod38fr** [rakudo/rakudo#3537]
Hello

While packaging rakudo for Debian, lintian issue the following error:
```
E: rakudo: arch-dependent-file-in-usr-share usr/share/perl6/runtime/dynext/libperl6_ops_moar.so
N: 
N:    This package installs an ELF binary in the /usr/share hierarchy, which
N:    is reserved for architecture-independent files.
```
`libperl6_ops_moar.so` should be installed in `/usr/lib` directory. 

With `moarvm`, `Configure.pl` provides a  `--libdir` option to specify where to install libraries

Could you provide a similar option for rakudo's Configure.pl ?

All the best

## Environment 
* Operating system:  Debian Linux (unstable)
* Compiler version (`perl6 -v`): 2020.02

**Comment by patrickbkr** [comment]
There was a similar request in #3093 The solution we currently have is using the `--rakudo-home=/some/path Configure.pl` switch to change the directory where all of rakudos runtime files are installed to. Is this a viable solution for the time being? (There is a long term goal to get rid of the libperl6_ops_moar.so thing.)

**Comment by dod38fr** [comment]
Yes. Now all files are installed in `/usr/lib/perl6` which is fine.

Thanks for the help

Dod

**Comment by dod38fr** [comment]
Unfortunately, with `perl Configure.pl --prefix=/usr --perl6-home=/usr/lib/perl6`, the installed `perl6` does not find core modules:
```
$ perl6
You may want to `zef install Readline` or `zef install Linenoise` or use rlwrap for a line editor

To exit type 'exit' or '^D'
> use CompUnit::Repository::Staging;
===SORRY!=== Error while compiling:
Could not find CompUnit::Repository::Staging in:
    inst#/home/domi/.raku
    inst#/usr/share/perl6/site
    inst#/usr/share/perl6/vendor
    inst#/usr/share/perl6/core
    ap#
    nqp#
    perl5#
> exit
```
The `PERL6_HOME` variable needs to be set so that core modules can be found:

```
 $ PERL6_HOME=/usr/lib/perl6 raku
You may want to `zef install Readline` or `zef install Linenoise` or use rlwrap for a line editor

To exit type 'exit' or '^D'
>  use CompUnit::Repository::Staging;
Nil
> exit
```

But this solution is not acceptable, because this breaks post-installation scripts when installing a perl6 modules packaged in a Debian package.

Is there a way to setup `/ust/lib/perl6` as the *default* perl6 home when `--perl6-home=/usr/lib/perl6` option is used when building rakudo ?

**Comment by patrickbkr** [comment]
@dod38fr What you experience is a build system bug that I believe was fixed just a few minutes ago with PR #3602. I'd be grateful for feedback whether those changes actually fix the problem you see. I'll reopen this bug for now. Can you close if you can confirm this is fixed?

**Comment by dod38fr** [comment]
Well, I've tried to apply a patch from #3602 on top of rakudo 2020.02.1 . Unfortunately, the resulting patch does not apply cleanly. I've tweaked the patch but I guess I did not resolve the conflicts correctly. The build show a lots of warnings like:
```Use of uninitialized value $str in substitution (s///) at /home/domi/debian-dev/build-area/rakudo-2020.02.1/3rdparty/nqp-configure/lib/NQP/Config.pm line 1420.
Use of uninitialized value $str in substitution (s///) at /home/domi/debian-dev/build-area/rakudo-2020.02.1/3rdparty/nqp-configure/lib/NQP/Config.pm line 1421.
Use of uninitialized value in concatenation (.) or string at /home/domi/debian-dev/build-area/rakudo-2020.02.1/tools/lib/NQP/Config/Rakudo.pm line 361.
```
and the installed perl6 fails to start with:

```$ perl6
Unhandled exception: While looking for 'ModuleLoader.moarvm': no such file or directory
   at <unknown>:1  (/usr/lib/perl6/runtime/perl6.moarvm:<dependencies+deserialize>)
```

All the best

**Comment by patrickbkr** [comment]
@dod38fr Did you also bump nqp-configure to include [PR#18](https://github.com/Raku/nqp-configure/commit/f1a2d8197138e9281150a2b47655908cee062a66) and nqp to include [PR#618](https://github.com/Raku/nqp/commit/cd87855866889c38d38427efc0599f666e852f29) respectively? The rakudo PR depends on those. I'm sorry I didn't communicate that clearly.

Maybe the best way forward is to just wait for `2020.0(4|5)` and make sure this works on master *before* the release is made. It'd be a pitty to screw up another release.

Tests I did on my local machine resulted in a working build with  both the nqp and rakudo homes in a different directory. May I kindly ask you to also give the master branch a try to make really sure this works on master?

**Comment by dod38fr** [comment]
@patrickbkr I indeed missed https://github.com/Raku/nqp/commit/cd87855866889c38d38427efc0599f666e852f29. With these patches rakudo build and execute without issues. 

Thanks for your help

**Comment by dod38fr** [comment]
@patrickbkr I'm facing again this issue where raku cannot find modules installed in `/usr/lib/perl6` (see [bug 969578](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969578) for details).

This is a regression compared to 2020.06.

Another way around is to install precomp files in /usr/share/perl6. This requires precomp files to be architecture independent, i.e. a precomp file built on armhf should work on amd64. 

Since moarvm files are now architecture independent, can I assume the same property with precomp files ?

All the best

**Comment by niner** [comment]
> Since moarvm files are now architecture independent, can I assume the same
> property with precomp files ?

Yes. Precomp files are just moarvm files with added dependency information

**Comment by dod38fr** [comment]
> Yes. Precomp files are just moarvm files with added dependency information

That's excellent news. Thanks for your fast reply..

All the best

**Comment by dod38fr** [comment]
And I'm back to square one :-(

With `perl Configure.pl --prefix=/usr --backends=moar`, all files are installed in `/usr/share/perl6` including `/usr/share/perl6/runtime/dynext/libperl6_ops_moar.so`.

Installing a shared library in `/usr/share/` is not allowed by Debian policy.

Is there a way out of this problem ?

All the best

**Comment by patrickbkr** [comment]
@dod38fr Was there a problem with the `--rakudo-home=/usr/lib/perl6` configure switch?

**Comment by patrickbkr** [comment]
I'll reopen until this is solved.

**Comment by dod38fr** [comment]
> @dod38fr Was there a problem with the `--rakudo-home=/usr/lib/perl6` configure switch?

Yes:
- Raku no longer finds pre-compiled files in `/usr/lib/perl6` (See [Debian bug 969578](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969578)). This is a serious issue that prevents raku 2020.08.2 to be released in Debian stable.
- Since pre-compiled files are arch independant, they should be installed in `/usr/share/perl6`.

**Comment by patrickbkr** [comment]
@dod38fr I think this is now fixed on the master branch. Any chance you can give it a try before the next release to make sure it will then work?

**Comment by patrickbkr** [comment]
The PR seems to have broken the build somehow. I had to revert. So this is open again. :-(

**Comment by Altai-man** [comment]
re revert: I have an impression that each time something in build system changes, somewhere it is not propagated and we got 

>Missing or wrong version of dependency 'gen/moar/stage2/NQPHLL.nqp' (from 'gen/moar/BOOTSTRAP/v6c.nqp')

So it is probably worth investigating what actually causes this one that bites us regularly.

**Comment by patrickbkr** [comment]
@Altai-man There is a WIP PR in #3918. The reason for the error is no mystery: The build runner or RUN_RAKUDO make command catches up the Rakudo home path of the installation directory (instead of the dummy rakudo home in `gen/build_rakudo_home`) and consequently tries to access a previous installations files should they exist. I tend to do a full rebuild including nuking the install dir when testing the build and thus don't notice such breakage and CI can't pick up such failures either. That's why I managed to break master twice with this error now.

**Comment by Altai-man** [comment]
@patrickbkr if this PR saves everyone builds and makes possible fixes of the current issues, I highly appreciate and admire your time spent on this.

**Comment by patrickbkr** [comment]
@dod38fr I have reapplied the fix in commit [8e6f7f0d2d1](https://github.com/rakudo/rakudo/commit/8e6f7f0d2d1f9b9bb69209602faead4b997bc0c3). So `Configure.pl --rakudo-home=some/dir` should now work again. The September release is planned for the end of the week. Could you give this a try before then to make sure it's working?

**Comment by dod38fr** [comment]
Hi

I've applied this commit on top of Rakudo 2020.08.2 and tried to build with nqp 2020.08.2 and moarvm 2020.08. The build fails with:
```
Unhandled exception: Cannot find method 'build-hll-sysconfig' on object of type Perl6::SysConfig
   at gen/moar/SysConfig.nqp:14  (/home/domi/debian-dev/build-area/rakudo-2020.08.2/blib/Perl6/SysConfig.moarvm:BUILD)
 from gen/moar/SysConfig.nqp:8  (/home/domi/debian-dev/build-area/rakudo-2020.08.2/blib/Perl6/SysConfig.moarvm:new)
 from gen/moar/rakudo.nqp:1  (rakudo.moarvm:<mainline>)
```

Is there some other patch to be applied ?

All the best

**Comment by patrickbkr** [comment]
@dod38fr Yes, you need to bump NQP to the latest commit (to include [b28db8914b](https://github.com/Raku/nqp/commit/b28db8914b769669a61311d72dff0576f6552bea)).

**Comment by dod38fr** [comment]
ok, I've updated nqp, then rakudo build failed due to a version problem.

So I've also updated moarv to latest version. Then nqp build fails with:
```  
Found /usr/bin/moar version 2020.08, which is too old. Wanted at least 2020.08-91-g590bac47e at /home/domi/debian-dev/build-area/nqp-2020.08.2+dfsg/3rdparty/nqp-configure/lib/NQP/Config.pm line 192.
```

I think I'm going to wait for next release before checking whether build works or not...

**Comment by dod38fr** [comment]
Hi

This problem is fixed with rakudo 2020.09 which I'm going to upload to Debian/unstable soon.

Thanks for your help
