### ISSUE TITLE
Regex captures + backtracking leak memory

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#4236]
## The Problem

The below is a golf of a memory leak problem I currently observe with <https://github.com/Raku/rakubrew.org>.

I'm not entirely sure I golfed correctly, because the rakubrew.org website has the code in a route and the leak occurs when hitting the website in parallel, and the golf below just uses `race` instead.

```
#!/usr/bin/env raku

my $md-template = 'resources/homepage.md.tmpl'.IO.slurp;
race for ^100000 {
    my $page = $md-template;
    $page ~~ s:g[ "(only-browser(" (.+) ")only-browser)" ] = "a";
}
```
With the template file filled with <https://gist.github.com/patrickbkr/33ff8521d9c646d90e3204691f25c84c/raw/0d2ca13cf9fb693661583bc6bf77eab82d0472a7/errors.md.tmpl> it mostly immediately aborts with one of the below errors.

When filling the template file with <https://gist.github.com/patrickbkr/33ff8521d9c646d90e3204691f25c84c/raw/0d2ca13cf9fb693661583bc6bf77eab82d0472a7/leaky.md.tmpl> it doesn't error, but fills my 16 GB of RAM in seconds.
I think it's a gradual thing. The longer the file gets the higher the chance that the script survives (longer).

```
A worker in a parallel iteration (hyper or race) initiated here:                               
  in block <unit> at ./test.raku line 4                                                        
                                                                                               
Died at:                                                                                       
    Type check failed in binding to parameter '<anon>'; expected List but got Match (Match.new(
:orig("(((...)                                                                                 
      in block  at ./test.raku line 6
```

```
A worker in a parallel iteration (hyper or race) initiated here:
  in block <unit> at ./test.raku line 4

Died at:
    Cannot call method 'fully-reified' on a null object
      in block  at ./test.raku line 6
```

```
A worker in a parallel iteration (hyper or race) initiated here:
  in block <unit> at ./test.raku line 4

Died at:
    Substring length (-625) cannot be negative
      in block  at ./test.raku line 6
```

## Environment

* Operating system: Fedora 33, Linux localhost.localdomain 5.10.19-200.fc33.x86_64 #1 SMP Fri Feb 26 16:21:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo(tm) v2021.02.1.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.02.

**Comment by patrickbkr** [comment]
I tried again on 2021.10. Now the following error joins the rows:

```
A worker in a parallel iteration (hyper or race) initiated here:
  in block <unit> at t.raku line 4

Died at:
    lang-call cannot invoke object of type 'VMNull' belonging to no language
      in block  at t.raku line 4
```

**Comment by patrickbkr** [comment]
Still happens on 2022.02.

**Comment by MasterDuke17** [comment]
I believe the leaking is (almost?) entirely because the loop is finishing before any garbage collection happens. So if you add something like `$*VM.request-garbage-collection if $_ %% 1_000` in your loop you should see a dramatically lower peak memory use.

**Comment by vrurg** [comment]
Since I was playing possible causes of #4871 I checked out this issue. I have two conclusions:

- The original problem is caused by the shared nature of `$/`. Two approaches are fixing the error: either the loop body is moved into a `sub` and that sub is invoked inside the loop; or `my $/;` is added to the loop body:
   ```raku
   race for ^100000 {
       my $/;
       my $page = $md-template;
       $page ~~ s:g[ "(only-browser(" (.+) ")only-browser)" ] = "a";
   }
   ```
- Memory is likely to be leaking or requesting for the garbage collecting doesn't work as intended. Adding the suggested `$*VM.request-garbage-collection if $_ %% 1_000;` line doesn't improve the situation as the script grows all the way up to 30-40GB either with or without the call.

**Comment by patrickbkr** [comment]
I can confirm, that the errors disappear when guarding `$/`. I'm thus changing the title of the bug.

**Comment by patrickbkr** [comment]
![memory_leak_rakubrew_org](https://user-images.githubusercontent.com/6307078/168795482-08458d5c-323e-4a87-b027-3d4733b94d66.png)
I just did a run of the rakubrew.org server (with caching disabled). (The rakubrew.org server is the app the script in the OP was golfed from.) The screenshot above shows the resource usage.
The first red arrow points at startup of the server, the last points at shutdown of the server.
The green arrows are each a single page load in firefox. The last green arrow are 4 quick consecutive refreshes.

So the first and second load each took ~2.5-3 GB of memory, the next few didn't use up much memory at all. Then hitting the page in parallel again triggers reserving more memory.

I wonder what component manages to reserve 2.5 GB of memory within a single load of the page, given that the server in essence is a Cro server and some regex substitutions similar to the one in the golf and nothing more. Also note that in this scenario (apart from the last 4 refreshes) there wasn't any concurrency involved. I'll try to see if I can golf this non-parallel effect as well.

**Comment by patrickbkr** [comment]
I golfed this down to a simple:

```
my $page = "abc" ~ "d" xx 8000;
$page ~~ m/ a (.+) c /;
$*VM.request-garbage-collection;
sleep 3;
```

This does a lot of backtracking. The memory use grows to over 2 GB (increase the number of "d"s and it goes as high as one likes) and stays that high even after the GC run.

**Comment by patrickbkr** [comment]
Given the above golf, my best guess is that temporary captures that are discarded during backtracking leak.

**Comment by niner** [comment]
Note that request-garbage-collection does not guarantee that all garbage is being collected. It only triggers a nursery collection and it depends on the heuristics of the GC if we do a gen2 collection.

**Comment by patrickbkr** [comment]
I ran the above golf with a patched moar that always does full GC runs. The memory usage doesn't go down.
Also the heap snapshot profiler doesn't see this memory. It shows peak memory usage at 47 MB.
Running with `valgrind --tool=DHAT` showed that the "offending" allocations are caused by the `clone` OP.

```
^1: 0x4B11D68: MVM_malloc (alloc.h:5)
#2: 0x4B12170: copy_to (VMArray.c:59)
#3: 0x4A769DD: MVM_interp_run (interp.c:1686)
#4: 0x4C146B0: MVM_vm_run_file (moar.c:505)
#5: 0x401FC3: main (main.c:474)
```

Running under gdb gives the following backtrace:
```
   at NQP::src/QRegex/NFA.nqp:672  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:mergesubstates)
 from NQP::src/QRegex/NFA.nqp:657  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:mergesubrule)
 from NQP::src/QRegex/NFA.nqp:699  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:mergesubstates)
 from NQP::src/QRegex/NFA.nqp:657  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:mergesubrule)
 from NQP::src/QRegex/Cursor.nqp:662  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:!protoregex_nfa)
 from NQP::src/QRegex/Cursor.nqp:630  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:quantifier)
 from NQP::src/QRegex/P6Regex/Grammar.nqp:209  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:quantified_atom)
 from NQP::src/QRegex/P6Regex/Grammar.nqp:193  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:termish)
 from NQP::src/QRegex/P6Regex/Grammar.nqp:182  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:termconj)
 from NQP::src/QRegex/P6Regex/Grammar.nqp:176  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:termalt)
 from NQP::src/QRegex/P6Regex/Grammar.nqp:168  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:termconjseq)
 from NQP::src/QRegex/P6Regex/Grammar.nqp:162  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:termaltseq)
 from <unknown>:1  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:termseq)
 from NQP::src/QRegex/P6Regex/Grammar.nqp:132  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPP6QRegex.moarvm:nibbler)
 from src/Perl6/Grammar.nqp:5760  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:nibble-in-cursor)
 from src/Perl6/Grammar.nqp:5772  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:nibbler)
 from src/Perl6/Grammar.nqp:255  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:nibble)
 from src/Perl6/Grammar.nqp:242  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:quibble)
 from src/Perl6/Grammar.nqp:3543  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:quote:sym<m>)
 from NQP::src/QRegex/Cursor.nqp:647  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:quote)
 from <unknown>:1  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:value:sym<quote>)
 from NQP::src/QRegex/Cursor.nqp:647  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:value)
 from <unknown>:1  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:term:sym<value>)
 from NQP::src/QRegex/Cursor.nqp:647  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:3739  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:termish)
 from NQP::src/HLL/Grammar.nqp:418  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:3786  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:963  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:891  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:statementlist)
 from NQP::src/HLL/Grammar.nqp:646  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from src/Perl6/Grammar.nqp:1344  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from src/Perl6/Grammar.nqp:839  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
 from src/Perl6/Grammar.nqp:554  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
 from NQP::src/QRegex/Cursor.nqp:1212  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/QRegex.moarvm:parse)
 from NQP::src/HLL/Compiler.nqp:552  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:parse)
 from NQP::src/HLL/Compiler.nqp:465  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from NQP::src/HLL/Compiler.nqp:500  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:run)
 from NQP::src/HLL/Compiler.nqp:503  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:)
 from NQP::src/HLL/Compiler.nqp:495  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:compile)
 from NQP::src/HLL/Compiler.nqp:166  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:eval)
 from NQP::src/HLL/Compiler.nqp:441  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from NQP::src/HLL/Compiler.nqp:331  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:112  (/home/patrickb/rrepos/rakudo/../install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from NQP::src/HLL/Compiler.nqp:289  (/home/patrickb/rrepos/nqp/../install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from src/main.nqp:81  (/home/patrickb/rrepos/rakudo/../install/share/perl6/runtime/perl6.moarvm:MAIN)
 from src/main.nqp:63  (/home/patrickb/rrepos/rakudo/../install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/patrickb/rrepos/rakudo/../install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/patrickb/rrepos/rakudo/../install/share/perl6/runtime/perl6.moarvm:<entry>)
```

**Comment by MasterDuke17** [comment]
The comment here (
https://github.com/Raku/nqp/blob/main/src/QRegex/NFA.nqp#L667-L673) seems
relevant.

**Comment by patrickbkr** [comment]
I believe the above backtrace was wrong. Here is one I believe is better:

```
(gdb) call MVM_dump_backtrace(tc)
   at NQP::src/QRegex/Cursor.nqp:428  (/home/patrickb/rrepos/install/share/nqp/lib/QRegex.moarvm:!cursor_start)
 from nfa-leak.raku:4  (<ephemeral file>:)
 from NQP::src/QRegex/Cursor.nqp:571  (/home/patrickb/rrepos/install/share/nqp/lib/QRegex.moarvm:!cursor_next)
 from <unknown>:1  (<ephemeral file>:)
 from SETTING::src/core.c/Str.pm6:1623  (/home/patrickb/rrepos/install/share/perl6/runtime/CORE.c.setting.moarvm:match)
 from nfa-leak.raku:4  (<ephemeral file>:<unit>)
 from nfa-leak.raku:1  (<ephemeral file>:<unit-outer>)
 from NQP::src/HLL/Compiler.nqp:196  (/home/patrickb/rrepos/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from NQP::src/HLL/Compiler.nqp:441  (/home/patrickb/rrepos/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from NQP::src/HLL/Compiler.nqp:331  (/home/patrickb/rrepos/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:112  (/home/patrickb/rrepos/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from NQP::src/HLL/Compiler.nqp:289  (/home/patrickb/rrepos/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from src/main.nqp:81  (/home/patrickb/rrepos/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from src/main.nqp:63  (/home/patrickb/rrepos/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/patrickb/rrepos/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/patrickb/rrepos/install/share/perl6/runtime/perl6.moarvm:<entry>)
```

**Comment by patrickbkr** [comment]
The above backtrace is still acurate with latest head as of today.
I got to that backtrace as follows:

- valgrind --tool=massif raku nfa-leak.raku
- ms_print massif.out.1234
    That reveals the point in MoarVM that causes the massive memory use: VMArray.c:59.
- Compile a MoarVM with --no-optimize --no-mimalloc --debug
- gdb /some/path/to/that/raku
- break interp.c:3691 # break on OP write_fhb (triggers on a `say`)
- run nfa-leak.raku
- break VMArray.c:59
- c
- call MVM_dump_backtrace(tc)

**Comment by niner** [comment]
This was fixed by https://github.com/Raku/nqp/commit/8a925a02f7ea9d65104243aa48f558dc85129d7b and https://github.com/Raku/nqp/commit/7f434701fec2523964cede6a61339020ed1e534b

Turns out it wasn't a memory leak in the strict sense after all. It was just accumulating a lot of garbage without triggering the garbage collector. It can be surprisingly hard to actually get the GC to collect garbage and free memory.

**Comment by patrickbkr** [comment]
> Turns out it wasn't a memory leak in the strict sense after all. It was just accumulating a lot of garbage without triggering the garbage collector. It can be surprisingly hard to actually get the GC to collect garbage and free memory.

Additionally if one manages to trigger the GC, the memory still isn't returned to the OS in this case (IIUC because the allocations are so small that the malloc/free implementation doesn't bother).
