### ISSUE TITLE
leaking NQPMu when coercion failed

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#4992]
```
class A {

}

class C {
    has A() $.attr is required;
}

my $c4 = C.new: attr => 42;
```

output:

```
Impossible coercion from 'Int' into 'A': method new returned a type object NQPMu
  in block <unit> at /home/dex/projects/raku/rakudobug/tmp.raku line 9
```

As vrurg stated on Reddit, `NQPMu` should not leak into user-land.

## Environment
* Operating system: Linux dexhome 5.15.0-2-amd64 #1 SMP Debian 5.15.5-1 (2021-11-26) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo™ v2022.06-33-g6dc2f92c9. Implementing the Raku® Programming Language v6.d. Built on MoarVM version 2022.06-2-gcc49dcf93.

**Comment by vrurg** [comment]
It looks like the bug has been fixed somewhere along the way of implementing new-disp version of coercion. Could you, please, check it out with the latest master?

**Comment by vrurg** [comment]
Closing as not reproducible on the master anymore.

**Comment by melezhik** [comment]
How to check this? My r3 test still shows the error message on the latest commit - https://gistcdn.githack.com/melezhik/eae4aef3bd23eec25ddb2cb80635fe45/raw/372c833d42ea60c5a1d222dc8277b45997fb3bbc/report.html

**Comment by vrurg** [comment]
That error is expected because `Int` is not coercible into `A`. The original problem was about the error message in which `NQPMu` was leaking. Now it produces correct error because there is no method.
